# Generated by Django 5.2.3 on 2025-07-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alerta', models.CharField(max_length=100)),
                ('mensaje_alerta', models.CharField(max_length=500)),
                ('DELETE_Alerta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=100)),
                ('DELETE_Barrio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias_Productos',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=150)),
                ('DELETE_CateP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('DELETE_Ciud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cupones_Descuento',
            fields=[
                ('id_cupon_desc', models.BigAutoField(primary_key=True, serialize=False)),
                ('descuento_porcentaje_cupon_desc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_monto_cupon_desc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_requeridos_cupon_desc', models.IntegerField()),
                ('nombre_cupon_desc', models.CharField(max_length=100)),
                ('descripcion_cupon_desc', models.CharField(max_length=300)),
                ('fecha_inicio_cupon_desc', models.DateField()),
                ('fecha_vencimiento_cupon_desc', models.DateField()),
                ('DELETE_Cupon_Desc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id_devolucion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('DELETE_Devo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('DELETE_Estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=200)),
                ('DELETE_Met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos_Financieros',
            fields=[
                ('id_movi_finan', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField()),
                ('total_movimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_movimiento', models.CharField(max_length=300)),
                ('DELETE_Movi_Finan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Origen_Puntos',
            fields=[
                ('id_origen_puntos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_origen', models.CharField(max_length=50)),
                ('DELETE_OP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('DELETE_Provin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=50)),
                ('DELETE_Event', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Movimientos',
            fields=[
                ('id_tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento', models.CharField(max_length=50)),
                ('DELETE_TM', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida_Productos',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad_medida', models.CharField(max_length=150)),
                ('DELETE_UMP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calles',
            fields=[
                ('id_calle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=100)),
                ('DELETE_Calle', models.BooleanField(default=False)),
                ('barrio_calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.barrios')),
            ],
        ),
        migrations.AddField(
            model_name='barrios',
            name='ciudad_barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.ciudades'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=50)),
                ('DELETE_Cli', models.BooleanField(default=False)),
                ('user_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cupones_Canjeado',
            fields=[
                ('id_cupon_canje', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_utilizado_canje', models.DateTimeField(auto_now_add=True)),
                ('DELETE_Cupon_Canje', models.BooleanField(default=False)),
                ('cliente_cupon_canje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.clientes')),
                ('cupon_descuento_cupon_canje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cupones_descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_direccion', models.CharField(max_length=100)),
                ('departamento_direccion', models.CharField(max_length=100)),
                ('referecia_direccion', models.CharField(max_length=100)),
                ('DELETE_Dir', models.BooleanField(default=False)),
                ('calle_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.calles')),
                ('usuario_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni_empleado', models.CharField(verbose_name=50)),
                ('telefono_empleado', models.CharField(max_length=50)),
                ('fecha_baja_empleado', models.DateTimeField()),
                ('DELETE_Emple', models.BooleanField(default=False)),
                ('user_empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cupones_descuento',
            name='estado_cupon_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados'),
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Comp', models.BooleanField(default=False)),
                ('estado_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('total_gastos_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ventas_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apertura_caja', models.DateTimeField()),
                ('cierre_caja', models.DateTimeField()),
                ('monto_apertura_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cierre_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_teorico_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones_caja', models.CharField(max_length=200)),
                ('DELETE_Caja', models.BooleanField(default=False)),
                ('estado_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Cajas_Compras',
            fields=[
                ('id_histo_caja_compras', models.BigAutoField(primary_key=True, serialize=False)),
                ('DELETE_Histo_Caja_Comp', models.BooleanField(default=False)),
                ('caja_histo_caja_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cajas')),
                ('compra_histo_caja_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.compras')),
                ('empleado_histo_caja_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro_producto', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_producto', models.DateTimeField(auto_now=True)),
                ('descripcion_producto', models.CharField(max_length=500)),
                ('marca_producto', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_unitario_producto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DELETE_Prod', models.BooleanField(default=False)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.categorias_productos')),
                ('unidad_medida_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.unidad_medida_productos')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Precio_Producto',
            fields=[
                ('id_histo_precio_prod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_histo_precio_prod', models.DateTimeField(auto_now_add=True)),
                ('precio_anterior_histo_precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo_histo_precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Histo_Precio_Prod', models.BooleanField(default=False)),
                ('empleado_histo_precio_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('producto_histo_precio_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Devoluciones',
            fields=[
                ('id_det_devo', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal_det_devo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_det_devo', models.CharField(max_length=200)),
                ('DELETE_Det_Devo', models.BooleanField(default=False)),
                ('devolucion_det_devo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.devoluciones')),
                ('producto_det_devo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compras',
            fields=[
                ('id_det_comp', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unidad_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_det_comp', models.IntegerField()),
                ('subtotal_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Det_Comp', models.BooleanField(default=False)),
                ('compra_dt_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.compras')),
                ('producto_dt_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Descartados',
            fields=[
                ('id_producto_descartado', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_prod_desc', models.DateField()),
                ('cantidad_prod_desc', models.PositiveIntegerField()),
                ('descripcion_prod_desc', models.CharField(max_length=250)),
                ('motivo_prod_desc', models.CharField(default='Vencimiento', max_length=100)),
                ('DELETE_Prod_Desc', models.BooleanField(default=False)),
                ('producto_prod_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('razon_social_proveedor', models.CharField(max_length=100)),
                ('telefono_proveedor', models.CharField(max_length=20)),
                ('cuit_proveedor', models.CharField(max_length=100)),
                ('correo_proveedor', models.EmailField(max_length=100)),
                ('DELETE_Prov', models.BooleanField(default=False)),
                ('estado_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes_Compras',
            fields=[
                ('id_orden_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_orden_compra', models.DateTimeField(auto_now_add=True)),
                ('DELETE_Orden_Comp', models.BooleanField(default=False)),
                ('empleado_orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('proveedor_orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.proveedores')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.proveedores'),
        ),
        migrations.CreateModel(
            name='Proveedores_Productos',
            fields=[
                ('id_prov_x_prod', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario_prov_x_prod', models.IntegerField()),
                ('DELETE_Prov_X_Prod', models.BooleanField(default=False)),
                ('producto_prov_x_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
                ('proveedor_prov_x_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedidos',
            fields=[
                ('id_det_pedi', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_det_pedi', models.IntegerField()),
                ('precio_unitario_det_pedi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DELETE_Det_Pedi', models.BooleanField(default=False)),
                ('orden_compra_det_pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.ordenes_compras')),
                ('provxprod_det_pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.proveedores_productos')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='provincia_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.provincias'),
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_actual_stock', models.IntegerField()),
                ('lote_stock', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('observaciones_stock', models.CharField(max_length=300)),
                ('DELETE_Stock', models.BooleanField(default=False)),
                ('producto_en_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Stock',
            fields=[
                ('id_historial_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_hstock', models.CharField(max_length=100)),
                ('fecha_movimiento_hstock', models.DateTimeField(auto_now_add=True)),
                ('stock_anterior_hstock', models.IntegerField()),
                ('stock_nuevo_hstock', models.IntegerField()),
                ('observaciones_hstock', models.CharField(max_length=300)),
                ('DELETE_Hstock', models.BooleanField(default=False)),
                ('empleado_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('stock_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.stocks')),
                ('tipo_movimiento_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.tipos_movimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones_Puntos',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('DELETE_Trans', models.BooleanField(default=True)),
                ('cliente_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.clientes')),
                ('origen_puntos_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.origen_puntos')),
            ],
        ),
        migrations.CreateModel(
            name='Puntajes',
            fields=[
                ('id_puntaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntos_acumulados', models.BigIntegerField()),
                ('puntos_utilizados', models.BigIntegerField()),
                ('DELETE_Puntaje', models.BooleanField(default=False)),
                ('transaccion_puntaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.transacciones_puntos')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('observaciones_venta', models.CharField(max_length=200)),
                ('DELETE_Vent', models.BooleanField(default=False)),
                ('caja_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cajas')),
                ('cliente_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.clientes')),
                ('empleado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('estado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Ventas',
            fields=[
                ('id_det_vent', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario_det_vent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_det_vent', models.IntegerField()),
                ('subtotal_det_vent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_det_vent', models.CharField(max_length=200)),
                ('DELETE_Det_Vent', models.BooleanField(default=False)),
                ('cupon_canje_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cupones_canjeado')),
                ('producto_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.productos')),
                ('venta_det_vent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_evento_caja', models.CharField(max_length=200)),
                ('fecha_evento_caja', models.DateTimeField(auto_now_add=True)),
                ('caja_event_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.cajas')),
                ('empleado_event_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.empleados')),
                ('tipo_event_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.tipo_evento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('caja_event_caja', 'empleado_event_caja', 'tipo_event_caja'), name='unique_evento_caja_combinacion')],
            },
        ),
        migrations.CreateModel(
            name='Venta_MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELETE_Vent_MetPag', models.BooleanField(default=False)),
                ('metodopago_vent_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.metodos_pago')),
                ('venta_vent_metpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.ventas')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metodopago_vent_metpag', 'venta_vent_metpag'), name='unique_venta_metodopago_combinacion')],
            },
        ),
    ]
